import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack/server";
import { Geist, DM_Mono } from "next/font/google";
import AppBg from "@/components/app-bg";
import GlobalShortcuts from "@/components/global-shortcuts";
import DbKeepalive from "@/components/db-keepalive";
import "./globals.css";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Stockflow",
  description: "Generated by XeKu 2026",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geist.variable} ${dmMono.variable} antialiased`}>
        <StackProvider app={stackServerApp}>
          <StackTheme theme={{
            dark: {
              background: "hsl(240, 15%, 7%)",
              foreground: "hsl(210, 40%, 96%)",
              card: "hsl(240, 14%, 10%)",
              cardForeground: "hsl(210, 40%, 96%)",
              popover: "hsl(240, 14%, 10%)",
              popoverForeground: "hsl(210, 40%, 96%)",
              primary: "hsl(239, 84%, 67%)",
              primaryForeground: "hsl(0, 0%, 100%)",
              secondary: "hsl(240, 10%, 16%)",
              secondaryForeground: "hsl(210, 40%, 80%)",
              muted: "hsl(240, 10%, 16%)",
              mutedForeground: "hsl(215, 16%, 47%)",
              accent: "hsl(240, 10%, 18%)",
              accentForeground: "hsl(210, 40%, 96%)",
              destructive: "hsl(350, 89%, 60%)",
              destructiveForeground: "hsl(0, 0%, 100%)",
              border: "hsl(240, 10%, 14%)",
              input: "hsl(240, 10%, 14%)",
              ring: "hsl(239, 84%, 67%)",
            },
            radius: "0.625rem",
          }}>
            <AppBg />
            <GlobalShortcuts />
            <DbKeepalive />
            {children}
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
